events_calendar/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from events_calendar import views
from events_calendar.views import ProposeEventCreateView, OrganizationListView, CurrentEventsListView
from .models import EngineSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'calendar'

sitemaps = {
    app_name: EngineSitemap
}

urlpatterns = [
    url(r'^$', views.EventsWithBaseFiltersListView.as_view(), name='home'),
    url(r'^home$', views.clear_filters, name='clear_filters'),
    url(r'^faq$', views.faq, name='faq'),
    url(r'^event/(?P<pk>[\d+]*)$', views.EventDetailsView.as_view(), name='details'),
    url(r'^comments/(?P<event_id>[\d+]*)$', views.CommentsListView.as_view(), name='comments'),
    url(r'^add_comment/(?P<event_id>[\d+]*)$', views.add_comment, name='add_comment'),
    url(r'^remove_comment/(?P<comment_id>[\d+]*)$', views.remove_comment, name='remove_comment'),
    url(r'^organization_events$', login_required(views.AdminOrganizationEvents.as_view()), name='organization_events'),
    url(r'^organization_events/create_event$', login_required(views.EventCreateView.as_view(success_url='/organization_events')), name='create_event'),
    url(r'^organization_events/edit_event/(?P<pk>[\d+]*)$', login_required(views.EventEditView.as_view()), name='edit_event'),
    url(r'^organization_events/edit_organization/(?P<pk>[\d+]*)$', login_required(views.OrganizationEditView.as_view(success_url='/organization_events')), name='edit_organization'),
    url(r'^subscribe$', views.subscribe, name='subscribe'),
    url(r'^my_feed$', login_required(views.EventsBySignedEventsAndOrganizationsListView.as_view()), name='filter_by_signed_organizations'),
    url(r'^searching_results$', views.searching_results, name='searching_results'),
    url(r'^searching_results/page/(\d+)$', views.searching_results),
    url(r'^suggest_an_event$', login_required(ProposeEventCreateView.as_view(success_url='/')), name='suggest_an_event'),
    url(r'^proposed_events$', login_required(views.ProposedEventsListView.as_view()), name='proposed_events'),
    url(r'^edit_proposed_event/(?P<pk>[\d+]*)$', login_required(views.ProposeEventEditView.as_view(success_url='/proposed_events')), name='edit_proposed_event'),
    url(r'^unsubscribe$', views.unsubscribe, name='unsubscribe'),
    url(r'^remove_proposed_event/(?P<event_id>[\d+]*)$', views.remove_proposed_event, name='remove_proposed_event'),
    url(r'^subscribe_on_organization/(?P<organization_id>[\d+]*)$', views.subscribe_on_organization, name='subscribe_on_organization'),
    url(r'^insert_into_google_calendar$', views.auth_calendar_api, name='insert_into_google_calendar'),
    url(r'^oauth2callback$', views.auth_return),
    url(r'^organizations$', login_required(OrganizationListView.as_view()), name='organization_list'),
    url(r'^current_events$', login_required(CurrentEventsListView.as_view()), name='current_events'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^(?P<organization_id>[^/]+)$', views.EventsByOrganizationListView.as_view(), name='filter_by_organization'),
]

kpi_events/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from kpi_events import settings
from loginsys import views

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    url(r'^96f3c45875e1.html/$', views.key),
    url(r'^ulogin/', include('django_ulogin.urls')),
    url(r'^', include('events_calendar.urls')),
]

loginsys/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from loginsys import views

app_name = 'loginsys'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^edit_user/$', login_required(views.UserEditView.as_view(success_url='/auth/edit_user')), name='edit_user'),
]

loginsys/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class customUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label="Ім'я", widget=forms.TextInput)
    last_name = forms.CharField(label='Прізвище', widget=forms.TextInput)
    email = forms.EmailField(label='email', widget=forms.EmailInput)

    class Meta:
        model = User
        fields = ('username', 'email','first_name', 'last_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserEditForm(forms.Form):
    email = forms.EmailField(max_length=50, label='Email')
    first_name = forms.CharField(max_length=50, label='Ім\'я')
    last_name = forms.CharField(max_length=50, label='Прізвище')
    image = forms.ImageField(label='')

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

loginsys/views.py
import random
import urllib

from django.views.generic import FormView
from django_ulogin.models import ULoginUser
from django_ulogin.signals import assign
from django.contrib import auth
from django.core.files.storage import default_storage
from django.shortcuts import render, redirect

# Create your views here.
from django.template.context_processors import csrf
from loginsys.forms import customUserCreationForm, UserEditForm


def catch_ulogin_signal(*args, **kwargs):
    """
    Обновляет модель пользователя: исправляет username, имя и фамилию на
    полученные от провайдера.

    В реальной жизни следует иметь в виду, что username должен быть уникальным,
    а в социальной сети может быть много "тёзок" и, как следствие,
    возможно нарушение уникальности.

    """
    user=kwargs['user']
    json=kwargs['ulogin_data']

    if kwargs['registered']:
        user.first_name = json['first_name']
        user.last_name = json['last_name']
        user.email = json['email']
        url_image = json['photo_big']
        link = 'images/users/'  + str(random.randint(0,1000)) + 'img_' + json['email']
        img = urllib.request.urlopen(url_image).read()
        f = default_storage.open(link, "wb+")
        f.write(img)
        f.close()
        user.profile.image = link
        user.save()


assign.connect(receiver=catch_ulogin_signal,
               sender=ULoginUser,
               dispatch_uid='customize.models')

def login(request):
    args = {}
    args.update(csrf(request))
    args['page_header'] = 'Аутентифікація'
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            args['login_error'] = "Пароль або ім'я користувача введені не правильно"
            return render(request, 'loginsys/login.html', args)

    else:
        if request.user.is_authenticated:
            return redirect('/')
        return render(request, 'loginsys/login.html', args)


def logout(request):
    auth.logout(request)
    return redirect('/')

def registration(request):
    add_event = request.GET.get('add_event', '-1')
    print(add_event)
    args = {}
    args['page_header'] = 'Реєстрація'
    args.update(csrf(request))
    args['form'] = customUserCreationForm()
    if request.POST:
        newuser_form = customUserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'], password=newuser_form.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect('/')
        else:
            args['form'] = newuser_form

    return render(request, 'loginsys/registration.html', args)

class UserEditView(FormView):
    template_name = 'loginsys/edit_user.html'
    form_class = UserEditForm

    def get_context_data(self, **kwargs):
        context = super(UserEditView, self).get_context_data()
        context['organizations'] = self.request.user.profile.signed_organizations.all()
        context['page_header'] = 'Редагування ' + self.request.user.first_name
        context['user'] = self.request.user
        return context

    def get_initial(self):
        initial = super(UserEditView, self).get_initial()
        initial['first_name'] = self.request.user.first_name
        initial['last_name'] = self.request.user.last_name
        initial['email'] = self.request.user.email
        initial['image'] = self.request.user.profile.image
        return initial

    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        user = self.request.user
        user.first_name = cleaned_data['first_name']
        user.last_name = cleaned_data['last_name']
        user.email = cleaned_data['email']
        user.profile.image = cleaned_data['image']
        user.save()
        return super(UserEditView, self).form_valid(form)


def key(request):
    return render(request, 'loginsys/96f3c45875e1.html')

loginsys/templates/loginsys/96f3c45875e1.html
ee0d66776b85

loginsys/templates/loginsys/edit_user.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    <br><br>
    <div class="col-lg-6 col-sm-12">
        <h6 class="text-info" style="color: #a1a1a1; font-size: large">Редагувати профіль:</h6>
        <form class="form-horizontal" action="{% url 'loginsys:edit_user' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Зберегти">
            <br><br><br><br><br><br><br>
        </form>
    </div>
    <div class="col-lg-6 col-sm-12">
        <h6 class="text-info" style="color: #a1a1a1; font-size: large">Мої підписки:</h6><br>
        {% for organization in organizations %}
            <form class="form-horizontal" id="subscribe_form" action="{% url 'calendar:unsubscribe' %}" method="post">
                {% csrf_token %}
                {% if user.username %}
                    <input type="hidden" name="organization" value="{{ organization.id }}">
                    {% if organization.image %}
                        {% thumbnail organization.image "30x30" format="PNG" crop="" as im %}
                            <a href="{% url 'calendar:filter_by_organization' organization.id %}"><img src="/media/{{ im.url }}" class="img-rounded" height="{{ im.height }}" width="{{ im.width }}"></a>
                        {% endthumbnail %}
                    {% endif %}
                    <a href="{% url 'calendar:filter_by_organization' organization.id %}"><span class="text-info" style="color: #859aff; font-size: larger">{{ organization.name }}</span></a>&nbsp;&nbsp;&nbsp;
                    <input id="subscribe_button" class="inline-block btn btn-default" type="submit" value="Відписатись">
                {% endif %}
            </form><br>
        {% endfor %}
        <br><br>
    </div>

    <script type="text/javascript">
        var someText = $('p:contains("Змінити:"):contains("Наразі:")').html();
        someText = someText.replace(/Змінити:/mig, '');
        $('p:contains("Змінити:"):contains("Наразі:")').html(someText);

        $('#id_image').before('<img src="/media/{{ user.profile.image }}" style="max-width: 200px"><br>Змінити:').attr('accept', 'image/jpeg,image/png');
        $('p').find('a').remove();
        window.addEventListener("DOMContentLoaded", function() {



	});
</script>
{% endblock %}

loginsys/templates/loginsys/login.html
{% extends 'base.html' %}
{% load ulogin_tags %}
{% block content %}
<br><br>
<div class="col-lg-8 col-sm-12">
    <form class="form-horizontal" action="{% url 'loginsys:login' %}" method="post">
        {% csrf_token %}
        <label class="control-label" for="inputUsername">Логін:</label>
        <input class="form-control" type="text" id="inputUsername" name="username" placeholder="Логин пользователя">
        <label class="control-label" for="inputPassword">Пароль:</label>
        <input class="form-control" type="password" id="inputPassword" name="password" placeholder="Пароль"><br>
        <button type="submit" class="btn btn-primary">Вхід</button>
        &nbsp;&nbsp;&nbsp;<a href="{% url 'loginsys:registration' %}">Реєстрація</a> <br><br>
        {% ulogin_widget %}
        <br><br>
        {% if login_error %}
            <label class="error-login">{{ login_error }}</label>
        {% endif %}

    </form>
</div>

{% endblock %}

loginsys/templates/loginsys/registration.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<div class="col-lg-8 col-sm-12">
    <form class="form-horizontal" action="{% url 'loginsys:registration' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <input id="reg" type="submit" value="Зареєструватися">
    </form>
    <br>
    <script type="text/javascript">
        $("label").addClass("control-label");
        $("input").addClass("form-control");
        $(".helptext").after("<br>");
        $("#reg").addClass("btn btn-primary");
        $("#reg").removeClass("form-control");
        $('label:contains("Ім\'я користувача:")').html("Логін:");
        $('.errorlist').addClass("error-login");
    </script>
</div>

{% endblock %}