events_calendar/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from events_calendar import views
from events_calendar.views import ProposeEventCreateView, OrganizationListView, CurrentEventsListView
from .models import EngineSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'calendar'

sitemaps = {
    app_name: EngineSitemap
}

urlpatterns = [
    url(r'^$', views.EventsWithBaseFiltersListView.as_view(), name='home'),
    url(r'^home$', views.clear_filters, name='clear_filters'),
    url(r'^faq$', views.faq, name='faq'),
    url(r'^event/(?P<pk>[\d+]*)$', views.EventDetailsView.as_view(), name='details'),
    url(r'^comments/(?P<event_id>[\d+]*)$', views.CommentsListView.as_view(), name='comments'),
    url(r'^add_comment/(?P<event_id>[\d+]*)$', views.add_comment, name='add_comment'),
    url(r'^remove_comment/(?P<comment_id>[\d+]*)$', views.remove_comment, name='remove_comment'),
    url(r'^organization_events$', login_required(views.AdminOrganizationEvents.as_view()), name='organization_events'),
    url(r'^organization_events/create_event$', login_required(views.EventCreateView.as_view(success_url='/organization_events')), name='create_event'),
    url(r'^organization_events/edit_event/(?P<pk>[\d+]*)$', login_required(views.EventEditView.as_view()), name='edit_event'),
    url(r'^organization_events/edit_organization/(?P<pk>[\d+]*)$', login_required(views.OrganizationEditView.as_view(success_url='/organization_events')), name='edit_organization'),
    url(r'^subscribe$', views.subscribe, name='subscribe'),
    url(r'^my_feed$', login_required(views.EventsBySignedEventsAndOrganizationsListView.as_view()), name='filter_by_signed_organizations'),
    url(r'^searching_results$', views.searching_results, name='searching_results'),
    url(r'^searching_results/page/(\d+)$', views.searching_results),
    url(r'^suggest_an_event$', login_required(ProposeEventCreateView.as_view(success_url='/')), name='suggest_an_event'),
    url(r'^proposed_events$', login_required(views.ProposedEventsListView.as_view()), name='proposed_events'),
    url(r'^edit_proposed_event/(?P<pk>[\d+]*)$', login_required(views.ProposeEventEditView.as_view(success_url='/proposed_events')), name='edit_proposed_event'),
    url(r'^unsubscribe$', views.unsubscribe, name='unsubscribe'),
    url(r'^remove_proposed_event/(?P<event_id>[\d+]*)$', views.remove_proposed_event, name='remove_proposed_event'),
    url(r'^subscribe_on_organization/(?P<organization_id>[\d+]*)$', views.subscribe_on_organization, name='subscribe_on_organization'),
    url(r'^insert_into_google_calendar$', views.auth_calendar_api, name='insert_into_google_calendar'),
    url(r'^oauth2callback$', views.auth_return),
    url(r'^organizations$', login_required(OrganizationListView.as_view()), name='organization_list'),
    url(r'^current_events$', login_required(CurrentEventsListView.as_view()), name='current_events'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^(?P<organization_id>[^/]+)$', views.EventsByOrganizationListView.as_view(), name='filter_by_organization'),
]

kpi_events/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from kpi_events import settings
from loginsys import views

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    url(r'^96f3c45875e1.html/$', views.key),
    url(r'^ulogin/', include('django_ulogin.urls')),
    url(r'^', include('events_calendar.urls')),
]

loginsys/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from loginsys import views

app_name = 'loginsys'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^edit_user/$', login_required(views.UserEditView.as_view(success_url='/auth/edit_user')), name='edit_user'),
]

templates/base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ua">
<head>
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-106618032-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments)};
        gtag('js', new Date());

        gtag('config', 'UA-106618032-1');
    </script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <meta name="description" content="KPIevents - календар подій КПІ.
     Події та заходи на території Київського політехнічного інституту та Києва.">
    <meta name="keywords" content="календар, кпі, події, івенти, заходи, календар подій,
     события, мероприятия, кпи, events, kpievents, kpi events, kpi">
    <meta property="og:image" content="https://events.kpi.ua/media/images/events_calendar/og.png">
    <link rel="shortcut icon" type="image/png" href="/media/images/events_calendar/logo_50x50.png">
    <link href="{% static 'bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/calendar.css' %}">
    {% block add_head %}
    {% endblock %}
    <title>{{ page_header }} | Календар подій КПІ</title>
</head>
<body>
<style>
    .mobile-version{
        left: 100px;
    }
    .desktop-version{
        left: 230px;
    }
</style>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu" aria-expanded="true">
            <span class="sr-only">Відкрити навігацію</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="{% url 'calendar:clear_filters' %}" style="text-decoration: none;"><img style="padding-left: 15px;" src="/media/images/events_calendar/logo_50x50_header.png">
        </a>&nbsp;<span style="font-size: 10px; color: whitesmoke; position: absolute; padding-top: 5px;">beta</span>

        <a style="text-decoration: none; color: black;" href="#"><span class="glyphicon glyphicon-filter navbar-toggle" data-toggle="collapse" data-target="#filters" aria-expanded="true"
                 style="padding: 8px; padding-top: 7px; cursor: pointer;" title="Відкрити фільтри"></span></a>

        <div style="position: relative;">
            <form id="search-field" class="nav-header" style="position: absolute; top: -38px; min-width: 140px; width: 30%;" method="get" action="{% url 'calendar:searching_results' %}">
                <input type="text" class="form-control" style="height: 25px;" placeholder="Пошук" name="text">
            </form>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="responsive-menu">
        <ul class="nav navbar-nav navbar-left">
            <li><a id="kpi" href="{% url 'calendar:clear_filters' %}">Календар подій КПІ</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.username %}
                <li>
                    {% if user.username %}
                        <a href="{% url 'calendar:suggest_an_event' %}" class="right" style="font-size: 40px; padding-top: 15px;"><span title="Запропонувати подію">+</span></a>
                    {% endif %}
                </li>
                <li>
                    {% thumbnail user.profile.image "30x30" format="PNG" crop="" as im %}
                        <img src="/media/{{ im.url }}" class="img-rounded" width="{{ im.width }}" height="{{ im.height }}" style="margin-top: 10px; float: left;">
                    {% endthumbnail %}
                    <a href="{% url 'loginsys:edit_user' %}" style="padding-left: 40px;">{{ user.first_name }}</a>
                </li>
                {% if user.profile.organization %}
                    {% thumbnail user.profile.organization.image "30x30" format="PNG" crop="" as im %}
                        <a href="{% url 'calendar:organization_events' %}"><img src="/media/{{ im.url }}" class="img-rounded" width="{{ im.width }}" height="{{ im.height }}" style="margin-top: 10px; float: left;"></a>
                    {% endthumbnail %}
                    <li>
                        <a href="{% url 'calendar:organization_events' %}">{{ user.profile.organization.name }}</a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'loginsys:logout' %}">Вийти</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'loginsys:login' %}" style="font-size: 40px; padding-top: 15px;"><span title="Запропонувати подію(Потрібна реєстрація)">+</span></a>
                </li>
                <li>
                    <a href="{% url 'loginsys:login' %}">Вхід і реєстрація</a>
                </li>
            {% endif %}
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<div class="container">
    <br><br>
    {% block content %}{% endblock %}
</div>
<footer id="footer" class="footer"><!--Footer-->
    <div class="container" >
        <p style="color: whitesmoke; padding-top: 12px; margin-bottom: 2px; text-align: center;">[ З усіх питань і верифікацією організації звертайтеся за адресою: <b>eventsKpi@gmail.com</b> ]</p>
        <p style="color: whitesmoke; margin-bottom: 2px; text-align: center;">[ Developed by <a href="https://www.facebook.com/profile.php?id=100011288523701" target="_blank" style="color: whitesmoke;"><b>Olexiy Yefimenko</b></a> olexiyyefimenko@gmail.com. Powered and hosted by <a href="https://hub.kpi.ua" target="_blank" style="color: whitesmoke"><b>KPI hub</b></a> ]</p>
        <p style="color: whitesmoke; text-align: center;">[ &#9400; <b><a style="color: whitesmoke;" href="{% url 'calendar:home' %}">KPI events</a></b>
            <a style="color: whitesmoke;" href="{% url 'calendar:faq' %}"><b>FAQ</b></a>
            {% thumbnail "images/events_calendar/logo_facebook.png" "20x20" format="PNG" crop="" as im %}
                &nbsp;<a href="https://www.facebook.com/KPIevents-2015503345374076/" target="_blank"><img src="/media/{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></a>
            {% endthumbnail %}
            {% thumbnail "images/events_calendar/logo_telegram.png" "20x20" format="PNG" crop="" as im %}
                &nbsp;<a href="https://t.me/eventskpi" target="_blank"><img src="/media/{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"></a>
            {% endthumbnail %}
            ]</p>
    </div>
</footer>
<script type="text/javascript">
    function footer() {
        if ($(document).height() <= $(window).height()){
            $("footer.footer").addClass("navbar-fixed-bottom");
        }else {
            $("footer.footer").removeClass("navbar-fixed-bottom");
        }
    }
    function changeSearchField() {
        if ($(window).width() <= 1000){
            $("#search-field").addClass("mobile-version").removeClass("desktop-version");
            $("#kpi").html('');
        }else {
            $("#search-field").removeClass("mobile-version").addClass("desktop-version");
            $("#kpi").html('Календар подій КПІ');
        }
    }
    $(document).ready(function () {
        footer();
        changeSearchField();
    });
    setInterval('footer()', 500);
    setInterval('changeSearchField()', 500);
</script>
</body>
</html>