events_calendar/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from events_calendar import views
from events_calendar.views import ProposeEventCreateView, OrganizationListView, CurrentEventsListView
from .models import EngineSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'calendar'

sitemaps = {
    app_name: EngineSitemap
}

urlpatterns = [
    url(r'^$', views.EventsWithBaseFiltersListView.as_view(), name='home'),
    url(r'^home$', views.clear_filters, name='clear_filters'),
    url(r'^faq$', views.faq, name='faq'),
    url(r'^event/(?P<pk>[\d+]*)$', views.EventDetailsView.as_view(), name='details'),
    url(r'^comments/(?P<event_id>[\d+]*)$', views.CommentsListView.as_view(), name='comments'),
    url(r'^add_comment/(?P<event_id>[\d+]*)$', views.add_comment, name='add_comment'),
    url(r'^remove_comment/(?P<comment_id>[\d+]*)$', views.remove_comment, name='remove_comment'),
    url(r'^organization_events$', login_required(views.AdminOrganizationEvents.as_view()), name='organization_events'),
    url(r'^organization_events/create_event$', login_required(views.EventCreateView.as_view(success_url='/organization_events')), name='create_event'),
    url(r'^organization_events/edit_event/(?P<pk>[\d+]*)$', login_required(views.EventEditView.as_view()), name='edit_event'),
    url(r'^organization_events/edit_organization/(?P<pk>[\d+]*)$', login_required(views.OrganizationEditView.as_view(success_url='/organization_events')), name='edit_organization'),
    url(r'^subscribe$', views.subscribe, name='subscribe'),
    url(r'^my_feed$', login_required(views.EventsBySignedEventsAndOrganizationsListView.as_view()), name='filter_by_signed_organizations'),
    url(r'^searching_results$', views.searching_results, name='searching_results'),
    url(r'^searching_results/page/(\d+)$', views.searching_results),
    url(r'^suggest_an_event$', login_required(ProposeEventCreateView.as_view(success_url='/')), name='suggest_an_event'),
    url(r'^proposed_events$', login_required(views.ProposedEventsListView.as_view()), name='proposed_events'),
    url(r'^edit_proposed_event/(?P<pk>[\d+]*)$', login_required(views.ProposeEventEditView.as_view(success_url='/proposed_events')), name='edit_proposed_event'),
    url(r'^unsubscribe$', views.unsubscribe, name='unsubscribe'),
    url(r'^remove_proposed_event/(?P<event_id>[\d+]*)$', views.remove_proposed_event, name='remove_proposed_event'),
    url(r'^subscribe_on_organization/(?P<organization_id>[\d+]*)$', views.subscribe_on_organization, name='subscribe_on_organization'),
    url(r'^insert_into_google_calendar$', views.auth_calendar_api, name='insert_into_google_calendar'),
    url(r'^oauth2callback$', views.auth_return),
    url(r'^organizations$', login_required(OrganizationListView.as_view()), name='organization_list'),
    url(r'^current_events$', login_required(CurrentEventsListView.as_view()), name='current_events'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^(?P<organization_id>[^/]+)$', views.EventsByOrganizationListView.as_view(), name='filter_by_organization'),
]

kpi_events/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from kpi_events import settings
from loginsys import views

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    url(r'^96f3c45875e1.html/$', views.key),
    url(r'^ulogin/', include('django_ulogin.urls')),
    url(r'^', include('events_calendar.urls')),
]

loginsys/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from loginsys import views

app_name = 'loginsys'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^edit_user/$', login_required(views.UserEditView.as_view(success_url='/auth/edit_user')), name='edit_user'),
]

events_calendar/models.py
from cuser.fields import CurrentUserField
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from oauth2client.contrib.django_util.models import CredentialsField
from django.contrib.sitemaps import Sitemap



class Index(models.Model):
    word = models.TextField(max_length=50)
    links = models.TextField(null=True)  # change on SET()

    def __str__(self):
        return self.links

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Назва')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

class Organization(models.Model):
    name = models.CharField(max_length=50, verbose_name='Найменування', null=False)
    image = models.ImageField(upload_to='images/organization', blank=True, default='images/organization/default_kpi_events.jpg')
    access_to_the_offer = models.BooleanField(default=False, blank=True)
    link_to_organization = models.CharField(max_length=50, verbose_name='Посилання на організацію', blank=True, null=True, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Організація'
        verbose_name_plural = 'Організації'

class Event(models.Model):
    name = models.CharField(max_length=100, verbose_name='Назва')
    description = models.TextField('Опис', blank=True, null=True)
    image = models.ImageField(upload_to='images/events_calendar', blank=True, default='images/events_calendar/default_300x200.png')
    creator_user = CurrentUserField(add_only=True, related_name='Юзер')
    creator = models.ForeignKey(Organization, verbose_name='Організація', null=True)
    start_date = models.DateTimeField('Дата початку')
    end_date = models.DateTimeField(verbose_name='Дата закінчення', blank=True, null=True)
    category = models.ForeignKey(Category, verbose_name='Категорія')
    place_of_event = models.CharField(max_length=100, verbose_name='Місце події', blank=True, null=True)
    fb_link = models.CharField(max_length=200, verbose_name='Посилання в fb', blank=True, null=True)
    web_site = models.CharField(max_length=200, verbose_name='Посилання на сайт події', blank=True, null=True)
    published = models.BooleanField(default=True, verbose_name='Опублікований')

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        from events_calendar.utils import add_index
        add_index(self.pk)

    def get_absolute_url(self):
        return "/event/%s" % self.pk

    class Meta:
        ordering = [
            '-start_date',
        ]
        verbose_name = 'Подія'
        verbose_name_plural = 'Події'

class Comment(models.Model):
    creator = CurrentUserField(add_only=True, related_name='Comment_creator')
    text = models.TextField('Коментар')
    event = models.ForeignKey(Event, verbose_name='Подія', null=True)
    time = models.DateTimeField(auto_now=True, verbose_name='Дата залишеного коментаря')

    def __str__(self):
        return self.creator.username

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коменти'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/users', blank=True, default='images/users/default.jpg')
    organization = models.ForeignKey(Organization, related_name='organization', verbose_name='Організація', null=True, blank=True)
    signed_organizations = models.ManyToManyField(Organization, related_name='organizations', blank=True, verbose_name='Організації')
    google_calendar_events = models.ManyToManyField(Event, blank=True, verbose_name='Події додані в гугл календар юзера')
    signed_events = models.ManyToManyField(Event, related_name='signed_events', blank=True, verbose_name='Події, які додані в "Мої події"')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Профіль'
        verbose_name_plural = 'Профілі'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

class EngineSitemap(Sitemap):
    priority = 0.5

    def items(self):
        return Event.objects.all()

    def lastmod(self, obj):
        return obj.start_date

    def changefreq(self, obj):
        return "daily"

events_calendar/forms.py
from django import forms
from django.forms import ModelForm
from events_calendar.models import Event, Organization


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'name',
            'description',
            'image',
            'start_date',
            'end_date',
            'category',
            'place_of_event',
            'web_site',
            'fb_link',
        ]

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = [
            'name',
            'image',
            'link_to_organization',
        ]

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

events_calendar/templates/events_calendar/calendar.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}


    <div class="row row-fluid">
        <br><br>
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 collapse navbar-collapse" id="filters">
            <div class="filter-style">
            {% if type != 'Моя лента событий' %}
                <form class="form-horizontal" method="post" action="{% url 'calendar:home' %}">
            {% else %}
                <form class="form-horizontal" method="post" action="{% url 'calendar:filter_by_signed_organizations' %}">
            {% endif %}
            <b class="main-filter-font">По даті:</b><br>
            <!--Hard code need to fix-->
            {% if current_date == '1' %}
                <input class="radio-inline" type="radio" name="date_filter" value="1" checked> Найближчі події<br>
                <input class="radio-inline" type="radio" name="date_filter" value="3"> Події на сьогодні<br>
                <input class="radio-inline" type="radio" name="date_filter" value="4"> Події на тиждень<br>
                <input class="radio-inline" type="radio" name="date_filter" value="2"> Минулі події<br>
            {% elif  current_date == '2'%}
                <input class="radio-inline" type="radio" name="date_filter" value="1"> Найближчі події<br>
                <input class="radio-inline" type="radio" name="date_filter" value="3"> Події на сьогодні<br>
                <input class="radio-inline" type="radio" name="date_filter" value="4"> Події на тиждень<br>
                <input class="radio-inline" type="radio" name="date_filter" value="2" checked> Минулі події<br>
            {% elif current_date == '3' %}
                <input class="radio-inline" type="radio" name="date_filter" value="1"> Найближчі події<br>
                <input class="radio-inline" type="radio" name="date_filter" value="3" checked> Події на сьогодні<br>
                <input class="radio-inline" type="radio" name="date_filter" value="4"> Події на тиждень<br>
                <input class="radio-inline" type="radio" name="date_filter" value="2"> Минулі події<br>
            {% elif current_date == '4' %}
                <input class="radio-inline" type="radio" name="date_filter" value="1"> Найближчі події<br>
                <input class="radio-inline" type="radio" name="date_filter" value="3"> Події на сьогодні<br>
                <input class="radio-inline" type="radio" name="date_filter" value="4" checked> Події на тиждень<br>
                <input class="radio-inline" type="radio" name="date_filter" value="2"> Минулі події<br>
            {% endif %}


            <br>
            <b class="main-filter-font">За категоріями:</b><br>
            {% csrf_token %}
            {% for category in categories %}
                {% if category in current_categories %}
                    <input class="checkbox-inline" type="checkbox" name="{{ category.name }}" value="{{ category.id }}" checked> {{ category.name }}<br>
                {% else %}
                    <input class="checkbox-inline" type="checkbox" name="{{ category.name }}" value="{{ category.id }}"> {{ category.name }}<br>
                {% endif %}
            {% endfor %}
            <br>
            <input type="submit" value="Фільтрувати" class="btn btn-primary btn-details center-block">
            </form>
            <span class="text-info" style="color: #a1a1a1;">{{ info_filter }}</span>
            </div>
            <br>
        </div>
        <div class="col-lg-10 col-md-9 col-sm-8 col-xs-12">
            <!--Hard code need to fix-->
            {% if user.username %}
                <ul class="nav nav-tabs">
                {% if type == 'Все события' %}
                    <li class="active"><a href="{% url 'calendar:home' %}">Всі події</a></li>
                    <li><a href="{% url 'calendar:filter_by_signed_organizations' %}">Мої події</a></li>
                    <li><a href="{% url 'calendar:organization_list' %}">Організації</a></li>
                    <li><a href="{% url 'calendar:current_events' %}">Поточні події</a></li>
                {% else %}
                    <li><a href="{% url 'calendar:home' %}">Всі події</a></li>
                    <li class="active"><a href="{% url 'calendar:filter_by_signed_organizations' %}">Мої події</a></li>
                    <li><a href="{% url 'calendar:organization_list' %}">Організації</a></li>
                    <li><a href="{% url 'calendar:current_events' %}">Поточні події</a></li>
                {% endif %}
                </ul>
                <br>
            {% endif %}
            {% for event in events %}
                <div class="row row-fluid">
                    <div class="col-lg-4 col-md-5 col-sm-5 col-xs-12">
                        {% if event.image != '' %}
                            <a href="{% url 'calendar:details' event.id %}">
                                {% thumbnail event.image "400x300" format="PNG" crop="" as im %}
                                    <img src="/media/{{ im.url }}" class="event-image">
                                {% endthumbnail %}
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                        <div class="text">
                            <span class="title-font main-text"><a href="{% url 'calendar:details' event.id %}">{{ event.name }}</a></span>&nbsp;
                            {% if request.user.profile.organization == event.creator %}
                                <a style="position: absolute;" href="{% url 'calendar:edit_event' event.id %}"><span title="Редагувати" class="glyphicon glyphicon-pencil"></span></a>
                            {% endif %}<br><br>
                            {% if event.creator.image %}
                                {% thumbnail event.creator.image "18x18" format="PNG" crop="" as im %}
                                    <img src="/media/{{ im.url }}" class="img-rounded" width="{{ im.width }}" height="{{ im.height }}">
                                {% endthumbnail %}
                            {% endif %}
                            {% if event.creator.link_to_organization != None %}
                                <a href="/{{ event.creator.link_to_organization }}">
                            {% else %}
                                <a href="/{{ event.creator.id }}">
                            {% endif %}
                            {{ event.creator.name }}</a> <span class="secondary-text" >&#8226; {{ event.category.name }}</span><br>


                            <span class="glyphicon glyphicon-time icon-secondary" style="padding-top: 5px;"></span>
                            <span class="secondary-text">{{ event.start_date }}</span>
                            {% if event.end_date.month == event.start_date.month and event.end_date.day == event.start_date.day %}
                                <span class="secondary-text"> - {{ event.end_date.hour }}:{% if event.end_date.minute < 10 %}0{{event.end_date.minute}}{% else %}{{event.end_date.minute}}{% endif %}</span>
                            {% elif event.end_date %}
                                <span class="secondary-text"> - {{ event.end_date }}</span>
                            {% endif %}
                            <br>

                            {% if event.place_of_event %}
                                <span class="glyphicon glyphicon-map-marker icon-secondary"></span>
                                <span class="secondary-text">{{ event.place_of_event }}</span><br>
                            {% endif %}
                            <br>
                            <p class="description-font" >{{ event.description|truncatechars:300 }}</p>
                        </div>
                    </div>
                </div>

                <br><br>
            {% endfor %}
        </div>



    </div>

    <br><br>

    <div class="row">
        <!--Hard code need to fix-->
        {% if type == 'Моя лента событий' %}
            <div style="text-align: center">
                {% load i18n %}
                <ul class="pagination pagination-sm">
                    {% if page_obj.has_previous %}
                        <li><a href="/my_feed?{{ page_obj.previous_page_number.querystring }}">&larr;</a>
                            {% else %}
                        <li class="disabled"><a>&larr;</a>
                    {% endif %}

                    {% for page in page_obj.pages %}
                        <li {% if page == page_obj.number %}class="active"{% endif %}>
                        {% if not page %}<li class="disabled"><a>...</a>
                        {% else %}
                            {% if page == page_obj.number %}
                                <a>{{ page }}</a>
                            {% else %}
                                <a href="/my_feed?page={{ page }}">{{ page }}</a>
                            {% endif %}
                        {% endif %}
                    </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li><a href="/my_feed?{{ page_obj.next_page_number.querystring }}">&rarr;</a>
                            {% else %}
                        <li class="disabled"><a>&rarr;</a>
                    {% endif %}
                </ul>
            </div>
        {% else %}
            <div style="text-align: center;">
                <ul class="pagination pagination-sm">
                    {% if page_obj.has_previous %}
                        <li><a href="?{{ page_obj.previous_page_number.querystring }}">&larr;</a>
                            {% else %}
                        <li class="disabled"><a>&larr;</a>
                    {% endif %}

                    {% for page in page_obj.pages %}
                        <li {% if page == page_obj.number %}class="active"{% endif %}>
                        {% if not page %}<li class="disabled"><a>...</a>
                        {% else %}
                            {% if page == page_obj.number %}
                                <a>{{ page }}</a>
                            {% else %}
                                <a href="?page={{ page }}">{{ page }}</a>
                            {% endif %}
                        {% endif %}
                    </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li><a href="?{{ page_obj.next_page_number.querystring }}">&rarr;</a>
                            {% else %}
                        <li class="disabled"><a>&rarr;</a>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
    <br><br><br><br>
{% endblock %}

events_calendar/templates/events_calendar/create_event.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block add_head %}
    <script src="{% static 'js/picker/js/bootstrap-datetimepicker.js' %}"></script>
    <link rel="stylesheet" href="{% static 'js/picker/css/bootstrap-datetimepicker.css' %}">
{% endblock %}
{% block content %}
    <br><br>
    <div class="col-lg-6 col-sm-8 col-xs-12">

        {% if type == 'create' %}
            <form class="form-horizontal" method="post" action="{% url 'calendar:create_event' %}" enctype="multipart/form-data">
        {% elif type == 'propose' %}
            <form class="form-horizontal" method="post" action="{% url 'calendar:suggest_an_event' %}" enctype="multipart/form-data" onsubmit="alert('Ваша подія буде розглянута адміністрацією KPI Events.');">
        {% endif %}
            {% csrf_token %}
            {{ form.as_table }}<br>
            <input type="submit" value="{{ button_info }}" class="btn btn-primary">
        </form>
    <br>
    </div>
    <script type="text/javascript">
        var placeholder = 'Ввести дату';
        var descriptionInfo = '  Посилання треба вводити в такому форматі: https://events.kpi.ua';
        $('#id_start_date').datetimepicker().attr('placeholder', placeholder);
        $('#id_end_date').datetimepicker().attr('placeholder', placeholder);
        $('#id_image').attr('accept', 'image/jpeg,image/png');
        $('label[for^="id_description"]').after(descriptionInfo);
        $('label[for^="id_name"]').before('*  ');
        $('label[for^="id_start_date"]').before('*  ');
        $('label[for^="id_category"]').before('*  ');
        var image_info = "  Рекомендований розмір: 300х200px. Розмір файлу не більш ніж 10Мб";
        $('label[for^="id_image"]').after(image_info);
    </script>
{% endblock %}

events_calendar/templates/events_calendar/current_events.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}

<br><br>
    <div class="row row-fluid">
        <div class="col-lg-10 col-md-9 col-sm-8 col-xs-12">
            <!--Hard code need to fix-->
            {% if user.username %}
                <ul class="nav nav-tabs">
                    <li><a href="{% url 'calendar:home' %}">Всі події</a></li>
                    <li><a href="{% url 'calendar:filter_by_signed_organizations' %}">Мої події</a></li>
                    <li><a href="{% url 'calendar:organization_list' %}">Організації</a></li>
                    <li class="active"><a href="{% url 'calendar:current_events' %}">Поточні події</a></li>
                </ul>
                <br>
            {% endif %}
            {% for event in events %}
                <div class="row row-fluid">
                    <div class="col-lg-4 col-md-5 col-sm-5 col-xs-12">
                        {% if event.image != '' %}
                            <a href="{% url 'calendar:details' event.id %}">
                                {% thumbnail event.image "400x300" format="PNG" crop="" as im %}
                                    <img src="/media/{{ im.url }}" class="event-image">
                                {% endthumbnail %}
                            </a>
                        {% endif %}
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-7 col-xs-12">
                        <div class="text">
                            <span class="title-font main-text"><a href="{% url 'calendar:details' event.id %}">{{ event.name }}</a></span>&nbsp;
                            {% if request.user.profile.organization == event.creator %}
                                <a style="position: absolute;" href="{% url 'calendar:edit_event' event.id %}"><span title="Редагувати" class="glyphicon glyphicon-pencil"></span></a>
                            {% endif %}<br><br>
                            {% if event.creator.image %}
                                {% thumbnail event.creator.image "18x18" format="PNG" crop="" as im %}
                                    <img src="/media/{{ im.url }}" class="img-rounded" width="{{ im.width }}" height="{{ im.height }}">
                                {% endthumbnail %}
                            {% endif %}
                            {% if event.creator.link_to_organization != None %}
                                <a href="/{{ event.creator.link_to_organization }}">
                            {% else %}
                                <a href="/{{ event.creator.id }}">
                            {% endif %}
                            {{ event.creator.name }}</a> <span class="secondary-text" >&#8226; {{ event.category.name }}</span><br>


                            <span class="glyphicon glyphicon-time icon-secondary" style="padding-top: 5px;"></span>
                            <span class="secondary-text">{{ event.start_date }}</span>
                            {% if event.end_date.month == event.start_date.month and event.end_date.day == event.start_date.day %}
                                <span class="secondary-text"> - {{ event.end_date.hour }}:{% if event.end_date.minute < 10 %}0{{event.end_date.minute}}{% else %}{{event.end_date.minute}}{% endif %}</span>
                            {% elif event.end_date %}
                                <span class="secondary-text"> - {{ event.end_date }}</span>
                            {% endif %}
                            <br>

                            {% if event.place_of_event %}
                                <span class="glyphicon glyphicon-map-marker icon-secondary"></span>
                                <span class="secondary-text">{{ event.place_of_event }}</span><br>
                            {% endif %}
                            <br>
                            <p class="description-font" >{{ event.description|truncatechars:300 }}</p>
                        </div>
                    </div>
                </div>

                <br><br>
            {% endfor %}
        </div>



    </div>

    <br><br>

    <div class="row">
        <div style="text-align: center;">
            {% load i18n %}
            <ul class="pagination pagination-sm">
                {% if page_obj.has_previous %}
                    <li><a href="/current_events?{{ page_obj.previous_page_number.querystring }}">&larr;</a>
                        {% else %}
                    <li class="disabled"><a>&larr;</a>
                {% endif %}

                {% for page in page_obj.pages %}
                    <li {% if page == page_obj.number %}class="active"{% endif %}>
                    {% if not page %}<li class="disabled"><a>...</a>
                    {% else %}
                        {% if page == page_obj.number %}
                            <a>{{ page }}</a>
                        {% else %}
                            <a href="/current_events?page={{ page }}">{{ page }}</a>
                        {% endif %}
                    {% endif %}
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li><a href="/current_events?{{ page_obj.next_page_number.querystring }}">&rarr;</a>
                        {% else %}
                    <li class="disabled"><a>&rarr;</a>
                {% endif %}
            </ul>

        </div>
    </div>
    <br><br><br><br>
{% endblock %}

events_calendar/templates/events_calendar/event_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block add_head %}
    <script src="{% static 'js/picker/js/bootstrap-datetimepicker.js' %}"></script>
    <link rel="stylesheet" href="{% static 'js/picker/css/bootstrap-datetimepicker.css' %}">
{% endblock %}
{% block content %}
<br><br>
<div class="col-lg-6 col-sm-8 col-xs-12">
    {% if type == 'event' %}
        <form class="form-horizontal" method="post" action="{% url 'calendar:edit_event' event.id %}" enctype="multipart/form-data">
    {% elif type == 'propose_event' %}
        <form class="form-horizontal" method="post" action="{% url 'calendar:edit_proposed_event' event.id %}" enctype="multipart/form-data">
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{{ button_info }}" class="btn btn-primary">
    </form>
    <br>
</div>
<script type="text/javascript">
{#        (function b(c) {#}
{#	        var d = /Змінити:/mig;#}
{#	        [].forEach.call(c.childNodes, function(a) {#}
{#	            3 == a.nodeType && (a.data = a.data.replace(d, ""));#}
{#	            1 == a.nodeType && b(a)#}
{#	        })#}
{##}
{#	    })(document.body);#}

        var someText = $('p:contains("Змінити:"):contains("Наразі:")').html();
        someText = someText.replace(/Змінити:/mig, '');
        $('p:contains("Змінити:"):contains("Наразі:")').html(someText);
        var placeholder = 'Ввести дату';
        $('#id_start_date').datetimepicker('setStartDate', '{{ start_time }}').attr('placeholder', placeholder);
        $('#id_end_date').datetimepicker().attr('placeholder', placeholder);
        $('#id_image').attr('accept', 'image/jpeg,image/png').before('<img src="/media/{{ event.image }}" style="max-width: 200px"><br>Змінити:');
        $('label[for^="id_name"]').before('*  ');
        $('label[for^="id_start_date"]').before('*  ');
        $('label[for^="id_category"]').before('*  ');
        $('p').find('a').remove();
        $('#image-clear_id').remove();
        $('label[for^="image-clear_id"]').remove();
        $('label[for^="id_image"]').remove();
</script>
{% endblock %}